name: autobuild

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Log in to GCR
      run: echo ${{ secrets.GCLOUD_SERVICE_KEY }} | base64 -d | docker login -u _json_key --password-stdin https://gcr.io/
    - name: Build Docker
      run: docker build -t gcr.io/pebble-rebirth/appstore-api:g${GITHUB_SHA::8} -f Dockerfile.cloudrun .
    - name: Push
      run: docker push gcr.io/pebble-rebirth/appstore-api:g${GITHUB_SHA::8}
